# Generated by Django 3.2.7 on 2021-11-30 16:15

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Kategori')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Başlık Bilgisi', max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(max_length=1000, verbose_name='İçerik')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('editedDate', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('categories', models.ManyToManyField(related_name='Blog', to='blog.KategoriModel')),
            ],
            options={
                'verbose_name_plural': 'Bloglar',
                'db_table': 'Blog',
                'ordering': ['id'],
            },
        ),
    ]
