# Generated by Django 3.2.7 on 2021-12-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211201_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=300)),
                ('title', models.CharField(max_length=50)),
                ('sendTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Iletisim',
                'verbose_name_plural': 'Iletisim',
                'db_table': 'Iletisim',
            },
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='blogId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel', verbose_name='Blog'),
        ),
    ]
