# Generated by Django 3.2.7 on 2021-12-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_kategorimodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimodel',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Kategori'),
        ),
    ]
