# Generated by Django 3.2.7 on 2021-12-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_kategorimodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategorimodel',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, unique=True, verbose_name='Kategori'),
        ),
    ]
